# Machine Learning

1. The machine learing is the feild of study<br>
   to give ability to a machine to learn without being explicitily programmed<br><br>
2. The ability of a machine to improve its performance based on previous results.

### Formal Definitaion:
The program can be said to learn from experience **E**<br>
with respect to some class of tasks **T** and performance measure **P**,<br>
if its perforamce at tasks in **T**, as measured by **P**, improves with experience **E**.
<pre>                                                     -Tom Mitchell</pre>

### Features of ML Algorithm
- Getting better at certain task with time.
- The act of remembering experience.
- Exploiting generalization similarity
- Learning with adaptation.

## Spam email detection
- **Task** - to detect spam email
- **Performance** - to tag a mail as spam
- **Experience** - to learn from number of times mail is tagged as email

- Spam email contains some specific keywords(like us, tweet, join today, offers, etc.)
- Emails without specific text, which has been marked as spam

## Application
- Association Analysis
- Supervised Learning
  - Classification
  - Regression/Prediction
- Unsupervised Learning
- Reinforcement Learning(Semi-Supervised)

**Unsupervised Learning:** Used when we dont know what to expect out of data

## Machine Learning vs Statistical Analysis
<pre>
<b>Machine Learning</b> is an algorithm                       <b>Statistical modelling</b> is the formalization
that can learn from data without relying               of relationships between variables in the form of 
on rules-based programming                             mathematical equations
</pre>

## Where it is used
- Face recognition
- speech recognizition
- handwriting recognition


#### Real life Examples
- facebook people you may know
- product recommendation
- virtual Assistants

## Association Analysis
- Simplest Form of analysis
- Given a set of transactions, find results that will predict 
  the occurance of an item based on the occurances of other items  in the transaction
<br><br>
#### Market Basket Analysis
<pre>
Record    Items Bought
1         bread, milk
2         bread, diaper, beer,egg
3         milk, diaper, beer, cola
4         bread, milk, diaper, beer
5         bread, milk, diaper, cola
</pre>

### Association Rule
- AN impllication expression of the form X-> Y<br>
  where X and Y are itemset.
- Example<br>
  {milk,diaper}-> beer

### Rule Evaluation Matrix
- Support(s)
- Confidence(c)

## Association Model

## Market basket analysis aims to give answers to the follwing:
- what are the purchase items?(items puirchased together/sequentially/seasonally)
- which product might benefit from advertising?
- why do customers buy certain products?
- what time of the day do they buy it?
- who are the customers?(students,families)

In [113]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
import numpy as np
dataset = [["Bread", "Milk","Beer"],
          ["Bread","Diapers","Eggs"],
          ["Milk","Diapers","Beer","Cola"],
          ["Bread","Milk","Diapers","Beer"],
          ["Bread","Milk","Cola"]]

In [8]:
te = TransactionEncoder()
te = te.fit(dataset) #extracts all the unique data from dataset
te_ary = te.transform(dataset) #converts array into hot coded matrix
print(te.columns_) 
print(te_ary)

df = pd.DataFrame(te_ary,columns  = te.columns_)
#print(df)

frequent_itemsets = apriori(df,min_support=0.3,use_colnames = True)
print(frequent_itemsets) #frequency of items


from mlxtend.frequent_patterns import association_rules
rules = association_rules(frequent_itemsets,metric="support",min_threshold=0.4)

print(rules)

['Beer', 'Bread', 'Cola', 'Diapers', 'Eggs', 'Milk']
[[ True  True False False False  True]
 [False  True False  True  True False]
 [ True False  True  True False  True]
 [ True  True False  True False  True]
 [False  True  True False False  True]]
    support               itemsets
0       0.6                 [Beer]
1       0.8                [Bread]
2       0.4                 [Cola]
3       0.6              [Diapers]
4       0.8                 [Milk]
5       0.4          [Beer, Bread]
6       0.4        [Beer, Diapers]
7       0.6           [Beer, Milk]
8       0.4       [Bread, Diapers]
9       0.6          [Bread, Milk]
10      0.4           [Cola, Milk]
11      0.4        [Diapers, Milk]
12      0.4    [Beer, Bread, Milk]
13      0.4  [Beer, Diapers, Milk]
        antecedants      consequents  antecedent support  consequent support  \
0            (Beer)          (Bread)                 0.6                 0.8
1           (Bread)           (Beer)                 0.8                 0.6
2            (Beer)        (Diapers)                 0.6                 0.6
3         (Diapers)           (Beer)                 0.6                 0.6
4            (Beer)           (Milk)                 0.6                 0.8
5            (Milk)           (Beer)                 0.8                 0.6
6         (Diapers)          (Bread)                 0.6                 0.8
7           (Bread)        (Diapers)                 0.8                 0.6
8            (Milk)          (Bread)                 0.8                 0.8
9           (Bread)           (Milk)                 0.8                 0.8
10           (Milk)           (Cola)                 0.8                 0.4
11           (Cola)           (Milk)                 0.4                 0.8
12           (Milk)        (Diapers)                 0.8                 0.6
13        (Diapers)           (Milk)                 0.6                 0.8
14     (Beer, Milk)          (Bread)                 0.6                 0.8
15    (Beer, Bread)           (Milk)                 0.4                 0.8
16    (Milk, Bread)           (Beer)                 0.6                 0.6
17           (Beer)    (Milk, Bread)                 0.6                 0.6
18           (Milk)    (Beer, Bread)                 0.8                 0.4
19          (Bread)     (Beer, Milk)                 0.8                 0.6
20     (Beer, Milk)        (Diapers)                 0.6                 0.6
21  (Beer, Diapers)           (Milk)                 0.4                 0.8
22  (Milk, Diapers)           (Beer)                 0.4                 0.6
23           (Beer)  (Milk, Diapers)                 0.6                 0.4
24           (Milk)  (Beer, Diapers)                 0.8                 0.4
25        (Diapers)     (Beer, Milk)                 0.6                 0.6

    support  confidence      lift  leverage  conviction
0       0.4    0.666667  0.833333     -0.08    0.600000
1       0.4    0.500000  0.833333     -0.08    0.800000
2       0.4    0.666667  1.111111      0.04    1.200000
3       0.4    0.666667  1.111111      0.04    1.200000
4       0.6    1.000000  1.250000      0.12         inf
5       0.6    0.750000  1.250000      0.12    1.600000
6       0.4    0.666667  0.833333     -0.08    0.600000
7       0.4    0.500000  0.833333     -0.08    0.800000
8       0.6    0.750000  0.937500     -0.04    0.800000
9       0.6    0.750000  0.937500     -0.04    0.800000
10      0.4    0.500000  1.250000      0.08    1.200000
11      0.4    1.000000  1.250000      0.08         inf
12      0.4    0.500000  0.833333     -0.08    0.800000
13      0.4    0.666667  0.833333     -0.08    0.600000
14      0.4    0.666667  0.833333     -0.08    0.600000
15      0.4    1.000000  1.250000      0.08         inf
16      0.4    0.666667  1.111111      0.04    1.200000
17      0.4    0.666667  1.111111      0.04    1.200000
18      0.4    0.500000  1.250000      0.08    1.200000
19      0.4    0.500000  0.833333     -0.08    0.800000
20      0.4    0.666667  1.111111      0.04    1.200000
21      0.4    1.000000  1.250000      0.08         inf
22      0.4    1.000000  1.666667      0.16         inf
23      0.4    0.666667  1.666667      0.16    1.800000
24      0.4    0.500000  1.250000      0.08    1.200000
25      0.4    0.666667  1.111111      0.04    1.200000

In [9]:
rules

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Beer),(Bread),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
1,(Bread),(Beer),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
2,(Beer),(Diapers),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
3,(Diapers),(Beer),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
4,(Beer),(Milk),0.6,0.8,0.6,1.000000,1.250000,0.12,inf
5,(Milk),(Beer),0.8,0.6,0.6,0.750000,1.250000,0.12,1.600000
6,(Diapers),(Bread),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
7,(Bread),(Diapers),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
8,(Milk),(Bread),0.8,0.8,0.6,0.750000,0.937500,-0.04,0.800000
9,(Bread),(Milk),0.8,0.8,0.6,0.750000,0.937500,-0.04,0.800000
10,(Milk),(Cola),0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000
11,(Cola),(Milk),0.4,0.8,0.4,1.000000,1.250000,0.08,inf
12,(Milk),(Diapers),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
13,(Diapers),(Milk),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
14,"(Beer, Milk)",(Bread),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
15,"(Beer, Bread)",(Milk),0.4,0.8,0.4,1.000000,1.250000,0.08,inf
16,"(Milk, Bread)",(Beer),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
17,(Beer),"(Milk, Bread)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
18,(Milk),"(Beer, Bread)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000
19,(Bread),"(Beer, Milk)",0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
20,"(Beer, Milk)",(Diapers),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
21,"(Beer, Diapers)",(Milk),0.4,0.8,0.4,1.000000,1.250000,0.08,inf
22,"(Milk, Diapers)",(Beer),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
23,(Beer),"(Milk, Diapers)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
24,(Milk),"(Beer, Diapers)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000
25,(Diapers),"(Beer, Milk)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000

In [18]:
rules['len of consequent']=pd.Series(map(len,rules['consequents']))
rules

In [29]:
rules['len of consequent'] = rules['consequents'].apply(lambda x:len(list(x)))
rules

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,len of consequent
0,(Beer),(Bread),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000,1
1,(Bread),(Beer),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000,1
2,(Beer),(Diapers),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,1
3,(Diapers),(Beer),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,1
4,(Beer),(Milk),0.6,0.8,0.6,1.000000,1.250000,0.12,inf,1
5,(Milk),(Beer),0.8,0.6,0.6,0.750000,1.250000,0.12,1.600000,1
6,(Diapers),(Bread),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000,1
7,(Bread),(Diapers),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000,1
8,(Milk),(Bread),0.8,0.8,0.6,0.750000,0.937500,-0.04,0.800000,1
9,(Bread),(Milk),0.8,0.8,0.6,0.750000,0.937500,-0.04,0.800000,1
10,(Milk),(Cola),0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000,1
11,(Cola),(Milk),0.4,0.8,0.4,1.000000,1.250000,0.08,inf,1
12,(Milk),(Diapers),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000,1
13,(Diapers),(Milk),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000,1
14,"(Beer, Milk)",(Bread),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000,1
15,"(Beer, Bread)",(Milk),0.4,0.8,0.4,1.000000,1.250000,0.08,inf,1
16,"(Milk, Bread)",(Beer),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,1
17,(Beer),"(Milk, Bread)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,2
18,(Milk),"(Beer, Bread)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000,2
19,(Bread),"(Beer, Milk)",0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000,2
20,"(Beer, Milk)",(Diapers),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,1
21,"(Beer, Diapers)",(Milk),0.4,0.8,0.4,1.000000,1.250000,0.08,inf,1
22,"(Milk, Diapers)",(Beer),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,1
23,(Beer),"(Milk, Diapers)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000,2
24,(Milk),"(Beer, Diapers)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000,2
25,(Diapers),"(Beer, Milk)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000,2

In [32]:
type(list(rules['consequents'][23]))

list

In [52]:
new_rules = rules[rules['len of consequent']>1]
new_rules

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,len of consequent
17,(Beer),"(Milk, Bread)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.2,2
18,(Milk),"(Beer, Bread)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.2,2
19,(Bread),"(Beer, Milk)",0.8,0.6,0.4,0.500000,0.833333,-0.08,0.8,2
23,(Beer),"(Milk, Diapers)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,2
24,(Milk),"(Beer, Diapers)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.2,2
25,(Diapers),"(Beer, Milk)",0.6,0.6,0.4,0.666667,1.111111,0.04,1.2,2

In [57]:
rules[rules['confidence'].astype('int')==1]
#dont use astype()

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,len of consequent
4,(Beer),(Milk),0.6,0.8,0.6,1.0,1.250000,0.12,inf,1
11,(Cola),(Milk),0.4,0.8,0.4,1.0,1.250000,0.08,inf,1
15,"(Beer, Bread)",(Milk),0.4,0.8,0.4,1.0,1.250000,0.08,inf,1
21,"(Beer, Diapers)",(Milk),0.4,0.8,0.4,1.0,1.250000,0.08,inf,1
22,"(Milk, Diapers)",(Beer),0.4,0.6,0.4,1.0,1.666667,0.16,inf,1

In [58]:
rules[rules['confidence'].between(0.9,1.1)]

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,len of consequent
4,(Beer),(Milk),0.6,0.8,0.6,1.0,1.250000,0.12,inf,1
11,(Cola),(Milk),0.4,0.8,0.4,1.0,1.250000,0.08,inf,1
15,"(Beer, Bread)",(Milk),0.4,0.8,0.4,1.0,1.250000,0.08,inf,1
21,"(Beer, Diapers)",(Milk),0.4,0.8,0.4,1.0,1.250000,0.08,inf,1
22,"(Milk, Diapers)",(Beer),0.4,0.6,0.4,1.0,1.666667,0.16,inf,1

In [140]:
new_rules_conf =rules[rules['confidence']>0.9]
new_rules_conf

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,len of consequent
4,(Beer),(Milk),0.6,0.8,0.6,1.0,1.250000,0.12,inf,1
11,(Cola),(Milk),0.4,0.8,0.4,1.0,1.250000,0.08,inf,1
15,"(Beer, Bread)",(Milk),0.4,0.8,0.4,1.0,1.250000,0.08,inf,1
21,"(Beer, Diapers)",(Milk),0.4,0.8,0.4,1.0,1.250000,0.08,inf,1
22,"(Milk, Diapers)",(Beer),0.4,0.6,0.4,1.0,1.666667,0.16,inf,1

### Find out all the rows of dataframe which have Cola in antecedant 

### Extension of above question
#### Find out all consequesnts of cola from data frame

In [101]:
new_rules_conf[new_rules_conf['antecedants'].apply(lambda x: 'Cola' in list(x))]

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,len of consequent
11,(Cola),(Milk),0.4,0.8,0.4,1.0,1.25,0.08,inf,1

In [119]:
#using sets
cart_item = ["Diapers","Milk"]
new_rules_conf[new_rules_conf['antecedants'].apply(lambda x: set(cart_item).issubset(x))]

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,len of consequent
22,"(Milk, Diapers)",(Beer),0.4,0.6,0.4,1.0,1.666667,0.16,inf,1

In [139]:
(new_rules_conf[new_rules_conf['antecedants'].apply(lambda x: 'Diapers' in list(x))]['consequents'].apply(lambda x:list(x))).tolist()

[['Milk'], ['Beer']]

## Application

1. Take an input from user
2. Based on the user input check that item in antecedant and suggest its consequent based on confidence
3. If user doesn't select the suggested item, let user enter another item
4. Suggest user another item based on user's item list and suggested item should not be the user's list
5. Keep repeating the process till user stops

### How to proceed:
1. load dataset
2. Get rules from purchase history filter based on confidence levels
3. display items that can be bought by the user, if there are no items then stop purchase
4. Take input item from user
5. Suggest consequent based on antecedant presence in the filtered rules
6. Take another user input, and determine if it is in suggestions, go back to step 3
   stop if user wants to stop purchase